name=CKC
version=1.2.5
author=PLGdevo <PLGgroup27@gmail.com>
maintainer=PLGdevo <PLGgroup27@gmail.com>
sentence=IoT communication library for CKC platform
paragraph=Supports WiFi, Ethernet, Zigbee, Modbus, Serial. Works with Arduino, ESP8266, ESP32, STM32, Raspberry Pi.
category=Communication
url=https://github.com/PLGdevo/CKC_LIB
architectures=*
includes=CKC.h
license=MIT