name=CKC
version=1.2.5
author=CKC
license=MIT
 "authors":
  {
    "name":  "PLGdevo",
    "email": "PLGgroup27@gmail.com",
    "url":   "https://github.com/PLGdevo",
    "maintainer": true
  },
  "repository":
  {
    "type": "git",
    "url": "https://github.com/PLGdevo/CKC_LIB.git"
  }
paragraph=It supports WiFi, Ethernet, Zigbee, Modbus, Serial. Works with boards like Arduino, ESP8266, ESP32, STM32, Raspberry Pi...
category=Communication
url=https://caothang.edu.vn
architectures=*
includes=CKC.h